openapi: 3.0.0
info:
  title: DP
  version: 1.0.0
servers:
  - url: http://localhost:1337/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/getAllUsersSki:
    get:
      tags:
        - default
      summary: getAllUsers
      description: Vrátí seznam uživatelských jmen všech uživatelů přihlášených v aplikaci
      parameters:
        - name: ''
          in: header
          schema:
            type: string
        - name: user
          in: query
          schema:
            type: string
          example: '{{userID}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/:
    get:
      tags:
        - default
      summary: Test GET
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Test POST
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                Key:
                  type: string
                  example: Value
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/private:
    get:
      tags:
        - default
      summary: /private (Auth0)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
